services:
  mysql:
    image: mysql:8.0
    container_name: techchallengeone_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: auto_repara
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pexample"]
      interval: 10s
      timeout: 5s
      retries: 20

  autoreparaapi:
    build:
      context: .
      dockerfile: Dockerfile   # se o Dockerfile está na raiz
    container_name: techchallengeone_api
    #depends_on:
    #  mysql:
    #    condition: service_healthy
    ports:
      - "5000:80"
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=auto_repara;User=root;Password=example;"
      Jwt__SecretKey: "sua-chave-super-secreta-muito-longa-para-256bits-change-me"
      Jwt__Issuer: "GestaoAutoRepara"
      Jwt__Audience: "GestaoAutoReparaUsers"
      Jwt__ExpirationMinutes: "60"
      ASPNETCORE_URLS: "http://+:80"
    restart: unless-stopped

volumes:
  mysql_data:
