apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "minha-senha"
  ConnectionStrings__DefaultConnection: "Server=mysql-svc;Port=3306;Database=auto_repara;Uid=root;Password=minha-senha;"
  Jwt__SecretKey: "sua-chave-super-secreta-muito-longa-para-256bits-change-me"
