apiVersion: v1
kind: Service
metadata: 
 name: auto-repara-svc
spec:
 selector: 
  app: auto-repara-api
 ports:
  - protocol: 'TCP'
    port: 80 #externo
    targetPort: 80 #interno
 type: LoadBalancer