apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306        # porta interna do Service
      targetPort: 3306  # porta do container
      nodePort: 30306   # porta exposta no Node (você escolhe dentro do range)
  type: NodePort
